// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krurlwonvkakfcwwvzey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtydXJsd29udmtha2Zjd3d2emV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTQ5NjUsImV4cCI6MjA3MTI3MDk2NX0.Hm1pBokIvd3kq3Kd5-X6b7PoKwPX8xddOBeO47yI8mQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});